import type { Metadata } from "next";
import { NavBar } from "../components/nav-bar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="nav-area">
          <NavBar />
        </div>
        <div className="content-area">
          {children}
        </div>
      </body>
    </html>
  );
}
